# 收集的重写规则

hostname = pipi.4kya.com, biz.caiyunapp.com, testflight.apple.com, spclient.wg.spotify.com

# 鸭奈飞去开屏
^http?:\/\/pipi\.4kya\.com/\/xgapp\.php\/v3\/advert.position.[^2](?<=position..) url reject

# 彩云天气Vip
^https?:\/\/biz\.caiyunapp\.com\/(membership_rights|v2\/user) url script-response-body https://raw.githubusercontent.com/Cool7Smile/QxConfig/main/Scripts/CaiYun.js

# Testflight 解除区域限制
^https?:\/\/testflight\.apple\.com\/v2\/accounts\/.*\/apps\/\d*/builds/\d*/install url request-body storefrontId" : ".*", request-body storefrontId" : "143441-19,29"

# Spotify Premuim解锁(By app2smile，>=iOS15)
# 建议重新登录,音质不能设置为超高
# 仓库地址 https://github.com/app2smile/rules
# 1.搜索界面 歌单/歌曲可以随意切换完全播放;2.音乐库已点赞歌曲随意切换完全播放
^https:\/\/spclient\.wg\.spotify\.com\/(bootstrap\/v1\/bootstrap|user-customization-service\/v1\/customize)$ url script-response-body https://raw.githubusercontent.com/Cool7Smile/QxConfig/main/Scripts/Spotify-Premuim.js
