# 收集的重写规则

hostname = pipi.4kya.com, biz.caiyunapp.com, testflight.apple.com

# 鸭奈飞去开屏
^http?:\/\/pipi\.4kya\.com/\/xgapp\.php\/v3\/advert.position.[^2](?<=position..) url reject

# 彩云天气Vip
^https?:\/\/biz\.caiyunapp\.com\/(membership_rights|v2\/user) url script-response-body https://raw.githubusercontent.com/Cool7Smile/QxConfig/main/Scripts/CaiYun.js

# Testflight 解除区域限制
^https?:\/\/testflight\.apple\.com\/v2\/accounts\/.*\/apps\/\d*/builds/\d*/install url request-body storefrontId" : ".*", request-body storefrontId" : "143441-19,29"
